## 读入数据

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import matplotlib.pyplot as plt
%matplotlib inline
# pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("../data/train.csv")
df.head(10)

Date stations observation     0     1     2     3     4     5     6  \
0  2014/1/1  station    AMB_TEMP    14    14    14    13    12    12    12   
1  2014/1/1  station         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   
2  2014/1/1  station          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37   
3  2014/1/1  station        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1   
4  2014/1/1  station          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9   
5  2014/1/1  station         NO2    16   9.2   8.2   6.9   6.8   3.8   6.9   
6  2014/1/1  station         NOx    17   9.8   8.7   8.6   8.5   5.3   8.8   
7  2014/1/1  station          O3    16    30    27    23    24    28    24   
8  2014/1/1  station        PM10    56    50    48    35    25    12     4   
9  2014/1/1  station       PM2.5    26    39    36    35    31    28    25   

   ...    14    15    16    17    18    19    20    21    22    23  
0  ...    22    22    21    19    17    16    15    15    15    15  
1  ...   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2  ...  0.37  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3  ...   0.1  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  
4  ...   2.5   2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8   1.5  
5  ...    11    11    22    28    19    12   8.1     7   6.9     6  
6  ...    14    13    25    30    21    13   9.7   8.6   8.7   7.5  
7  ...    65    64    51    34    33    34    37    38    38    36  
8  ...    52    51    66    85    85    63    46    36    42    42  
9  ...    36    45    42    49    45    44    41    30    24    13  

[10 rows x 27 columns]

In [ ]:
df = df.loc[df.observation == 'PM2.5']
df.head()


Date stations observation   0   1   2   3   4   5   6  ...  14  15  \
9   2014/1/1  station       PM2.5  26  39  36  35  31  28  25  ...  36  45   
27  2014/1/2  station       PM2.5  21  23  30  30  22  18  13  ...  53  43   
45  2014/1/3  station       PM2.5  19  25  27  20  16  14  15  ...  32  36   
63  2014/1/4  station       PM2.5  27  27  14  20  22  24  26  ...  62  55   
81  2014/1/5  station       PM2.5  80  80  76  81  75  66  70  ...  64  73   

    16  17  18  19  20  21  22  23  
9   42  49  45  44  41  30  24  13  
27  43  45  46  32  16  19  22  26  
45  34  45  40  41  23  29  23  37  
63  56  67  78  83  90  75  85  82  
81  57  57  53  70  70  60  68  66  

[5 rows x 27 columns]

In [4]:
data = df.filter(regex="[^a-z]")
# data['month'] = pd.DatetimeIndex(data['Date']).month
# data['day'] = pd.DatetimeIndex(data['Date']).day
data = data.drop(['Date'],axis=1)
# cols = data.columns
# data[cols]=data[cols].astype('int64')

In [5]:
data.head(10)

0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20  \
9    26  39  36  35  31  28  25  20  19  30  ...  36  45  42  49  45  44  41   
27   21  23  30  30  22  18  13  13  11  22  ...  53  43  43  45  46  32  16   
45   19  25  27  20  16  14  15   8   4   9  ...  32  36  34  45  40  41  23   
63   27  27  14  20  22  24  26  33  48  50  ...  62  55  56  67  78  83  90   
81   80  80  76  81  75  66  70  65  66  57  ...  64  73  57  57  53  70  70   
99   66  55  46  46  46  42  35  35  40  45  ...  62  59  61  50  60  62  62   
117  41  32  35  31  33  25  36  28  33  29  ...  62  61  47  54  57  59  61   
135  48  53  60  60  52  47  45  50  43  40  ...  35  36  36  32  33  33  34   
153  18  15   9   9  14  15  20  16  23  16  ...  20  20  20  18  18  22  15   
171   6   7   7   0   0   1   1   7   7   8  ...  23  20  18  15  16  10   6   

     21  22  23  
9    30  24  13  
27   19  22  26  
45   29  23  37  
63   75  85  82  
81   60  68  66  
99   50  45  43  
117  43  39  38  
135  21  15  13  
153  11   1   1  
171  11  22  28  

[10 rows x 24 columns]

In [6]:
data = data.convert_objects(convert_numeric=True)

C:\Users\yinyajun-hj\AppData\Local\Programs\Python\Python35\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


## 异常值检测

In [7]:
# 检查是否有空值
df.isnull().any().any()

False

In [8]:
# 检查是否有异常值，zscore>3
data[data.apply(lambda x: np.abs(x - x.mean()) / x.std() > 3).any(axis=1)]

0   1   2   3   4   5   6   7   8   9  ...  14  15   16   17   18   19  \
63    27  27  14  20  22  24  26  33  48  50  ...  62  55   56   67   78   83   
81    80  80  76  81  75  66  70  65  66  57  ...  64  73   57   57   53   70   
99    66  55  46  46  46  42  35  35  40  45  ...  62  59   61   50   60   62   
117   41  32  35  31  33  25  36  28  33  29  ...  62  61   47   54   57   59   
315   17  26  25  24  10   7  11  16  19   9  ...  81  90  109  109  105  102   
333   64  52  36  41  46  48  38  21  11  11  ...  50  57   66   72   77   72   
351   61  59  60  48  53  60  66  53  55  57  ...  51  47   44   46   46   39   
675   65  61  57  46  27  14   5   4  11  21  ...  59  47   49   43   35   18   
891    9   4   4   7   7   4   1  14  24  31  ...  51  70   86   86   74   70   
909   62  63  64  61  57  43  34  26  26  36  ...  69  66   66   73   71   60   
927   46  46  37  28  32  42  42  49  57  80  ...  31  47   69   97   98   94   
981   36  37  37  40  47  48  62  72  76  78  ...  52  62   59   59   61   68   
1053  40  44  46  44  43  51  53  50  51  57  ...  52  47   53   59   73   74   
2187  25  28  17   6  10  20  25  21  10  15  ...  56  39   26   49   49   84   
2205  18  49  70  76  25   7   7   7  15  20  ...  26  27   27   20   13   37   
2241   7   8  15  26  31  53  51  64  30  28  ...  67  63   63   63   21    9   
3609  92  97  90  76  73  70  70  59  58  55  ...  59  46   44   29   27   26   
3735  32  41  50  46  45  36  35  36  33  29  ...  94  88   70   71   81   83   
4221  49  57  53  65  64  68  52  42  31  27  ...  21  17   24   23   18   23   

       20   21  22  23  
63     90   75  85  82  
81     70   60  68  66  
99     62   50  45  43  
117    61   43  39  38  
315   106  107  92  80  
333    75   72  69  62  
351    18   19  23  34  
675     9    0   0   1  
891    77   85  78  68  
909    44   45  44  49  
927    85   68  49  16  
981    69   57  49  45  
1053   83   82  70  51  
2187   53  112  69  80  
2205   63   42  26  29  
2241   17   15  22  15  
3609   27   35  35  41  
3735   63   53  38  29  
4221   21   27  14  10  

[19 rows x 24 columns]

In [9]:
data.apply(lambda x: x.mean())

0     19.137500
1     18.270833
2     17.625000
3     16.737500
4     16.154167
5     16.041667
6     15.766667
7     16.250000
8     17.104167
9     19.087500
10    21.404167
11    22.916667
12    24.345833
13    25.012500
14    26.404167
15    26.779167
16    27.341667
17    27.241667
18    26.341667
19    25.383333
20    24.162500
21    22.883333
22    21.379167
23    20.170833
dtype: float64

In [10]:
data.apply(lambda x: x.std())

0     15.164711
1     15.616668
2     15.423485
3     15.328818
4     14.243151
5     14.008901
6     13.669582
7     13.623601
8     14.195644
9     15.294482
10    16.293053
11    16.265621
12    17.190332
13    17.399197
14    17.955989
15    17.248285
16    17.367307
17    18.313630
18    18.026710
19    18.250550
20    17.779997
21    17.459425
22    15.829967
23    15.221378
dtype: float64

可见，zscore大于3的值基本上都是因为pm2.5超高造成的，这实际上不是异常数据。

In [11]:
# 发现负值，检查负值
data[data.apply(lambda x:x<0).any(axis=1)]

0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20  \
351   61  59  60  48  53  60  66  53  55  57  ...  51  47  44  46  46  39  18   
1089  38  27  24  18  13  15  12  11   5   6  ...  21  20  16  17  21  27  22   
1215  15   9  13   6   9   8   7   8  13  13  ...  35  24  21  17  26  24  25   
1341  22  19  15  24  29  34  33  34  35  41  ...  55  -1  48  45  35  38  48   
1521  11  14  10   4   4  11  11   5  -1  -1  ...   1   3   3   5   4   7   2   
1539   2  -1  -1  -1   4   7  14   8   5  -1  ...   9   3  14  13  10  -1  -1   
1557   9  -1  -1  -1  -1  -1  -1  -1  -1  -1  ...   9  15  15   9  19  17  24   
1665   8   9   6   6   1   4   4   1   0   0  ...   7   4   5  14  14   7   0   
2295  11  12   7   0   0   0   4   4   7   4  ...  -1  27  22  17  21  21  14   
3879   0   0   0   0   1   1  13  19  23  14  ...  18  18  18  -1  -1  -1  -1   
3897  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  ...  19  19  19  12   3   6  11   
4095  27  15  11  11  14  15  15  17  23  24  ...   7  12  15  25  37  36  34   

      21  22  23  
351   19  23  34  
1089  22  14  15  
1215  26  21  16  
1341  44  32  17  
1521   2   2   2  
1539  -1   9   9  
1557  19  21  14  
1665   6   6   6  
2295  14  14  14  
3879  -1  -1  -1  
3897  11   8   6  
4095  22  13   4  

[12 rows x 24 columns]

In [12]:
# 处理负值
# 可以发现直接用0填充是不合理的
# 考虑到监测的连续性，采用均值填充比较合理
# 由于涉及到的数据不算很多，也可以删除处理（这里采取删除）

## 生成训练集

In [13]:
train_x = []
train_y = []
for i in range(15):
    x = data.iloc[:, i:i + 9]
    x.columns = np.array(
        range(9))  #notice if we don't set columns name, it will have different columns name in each iteration
    #     d=data.iloc[:,-2:]
    #     d.columns=[9,10]
    #     x=x.join(d)
    y = data.iloc[:, i + 9]
    y.columns = np.array(range(1))
    train_x.append(x)
    train_y.append(y)


In [14]:
# 如何合并？merge,join或concat
# merge用于列，join用于index，concat相当于union或者outer join（axis=1）
a = data.iloc[:, -2:]
b = data.iloc[:, :9]
# pd.concat([a,b],axis=1).head()
a.join(b).head()


22  23   0   1   2   3   4   5   6   7   8
9   24  13  26  39  36  35  31  28  25  20  19
27  22  26  21  23  30  30  22  18  13  13  11
45  23  37  19  25  27  20  16  14  15   8   4
63  85  82  27  27  14  20  22  24  26  33  48
81  68  66  80  80  76  81  75  66  70  65  66

In [15]:
train_x=pd.concat(train_x)
train_y=pd.concat(train_y)  
train_x.head(10)

0   1   2   3   4   5   6   7   8
9    26  39  36  35  31  28  25  20  19
27   21  23  30  30  22  18  13  13  11
45   19  25  27  20  16  14  15   8   4
63   27  27  14  20  22  24  26  33  48
81   80  80  76  81  75  66  70  65  66
99   66  55  46  46  46  42  35  35  40
117  41  32  35  31  33  25  36  28  33
135  48  53  60  60  52  47  45  50  43
153  18  15   9   9  14  15  20  16  23
171   6   7   7   0   0   1   1   7   7

In [16]:
# 将含有负值的记录删除
cond1 = train_x.apply(lambda x: x > 0).all(axis=1)
x = train_x[cond1]
y = train_y[cond1]
cond2 = y.apply(lambda x: x > 0)
x = x[cond2]
y = y[cond2]
train_x = x
train_y = y
len(train_y)


2886

In [17]:
# 总共少的训练样本
3600-2886

714

In [18]:
# 标准化
class standardScaler(object):
    def __init__(self, train_x):
        m_ = train_x.apply(lambda x:x.mean())
        s_ = train_x.apply(lambda x:x.std())
        self.m_ = np.array(m_, float)
        self.s_ = np.array(s_, float)
    
    def fit(self, df):
        df = df.sub(self.m_).divide(self.s_)
        return df
    
ss = standardScaler(train_x)
train_x = ss.fit(train_x)
train_x.head()

0         1         2         3         4         5         6  \
9   0.239922  1.020083  0.771865  0.653271  0.362212  0.139817 -0.070005   
27 -0.083153 -0.004348  0.392257  0.343498 -0.187390 -0.462259 -0.785383   
45 -0.212383  0.123706  0.202453 -0.276048 -0.553792 -0.703089 -0.666154   
63  0.304537  0.251760 -0.620030 -0.276048 -0.187390 -0.101014 -0.010390   
81  3.729130  3.645188  3.302582  3.503185  3.049157  2.427705  2.612663   

           7         8  
9  -0.390747 -0.459290  
27 -0.804645 -0.929309  
45 -1.100287 -1.340575  
63  0.377921  1.244528  
81  2.270027  2.302070

In [19]:
train_x = np.array(train_x,float)
train_y = np.array(train_y,float)
# add bias to train dataset
train_x = np.concatenate((np.ones((train_x.shape[0],1)),train_x),axis=1)
train_x

array([[ 1.        ,  0.23992168,  1.02008301, ..., -0.0700051 ,
        -0.3907468 , -0.4592902 ],
       [ 1.        , -0.08315315, -0.00434833, ..., -0.78538329,
        -0.80464503, -0.92930892],
       [ 1.        , -0.21238308,  0.12370559, ..., -0.66615359,
        -1.10028661, -1.34057529],
       ..., 
       [ 1.        , -0.9231477 , -0.45253704, ...,  0.58575824,
         0.25966469, -0.04802383],
       [ 1.        ,  0.56299651,  0.50786734, ...,  0.76460279,
         0.55530628, -0.16552851],
       [ 1.        , -1.37545246, -1.02877968, ...,  0.10883945,
        -0.56813176, -0.16552851]])

In [20]:
train_y

array([ 30.,  22.,   9., ...,  19.,  23.,  29.])

## 线性回归

In [21]:
# 初始化
w = np.random.normal(0,0.001,len(train_x[0]))
lr = 1.0
epoch_num = 20000

In [22]:
# 训练, AdaGrad
loss_history=[]
sum_grad = np.zeros(len(train_x[0]))
for i in range(epoch_num):
    y_hat = np.dot(train_x, w) # MxN * Nx1 = Mx1
    loss = ((train_y - y_hat) ** 2).mean()
    grad = np.dot(train_x.transpose(), y_hat - train_y) # NxM * Mx1 = Nx1
    sum_grad += grad ** 2
    ada_lr = lr / np.sqrt(sum_grad)
    w -= ada_lr * grad
    
    loss_history.append(loss)
    if i % 1000 == 0:
        print("Step: {0}, Loss: {1}".format(i, loss))

Step: 0, Loss: 1014.978771890307
Step: 1000, Loss: 40.67475484795355
Step: 2000, Loss: 40.33201668831543
Step: 3000, Loss: 40.31865214690424
Step: 4000, Loss: 40.3179226722865
Step: 5000, Loss: 40.31787989369237
Step: 6000, Loss: 40.317877349847805
Step: 7000, Loss: 40.317877198187645
Step: 8000, Loss: 40.31787718914164
Step: 9000, Loss: 40.31787718860204
Step: 10000, Loss: 40.317877188569845
Step: 11000, Loss: 40.31787718856793
Step: 12000, Loss: 40.317877188567806
Step: 13000, Loss: 40.317877188567806
Step: 14000, Loss: 40.3178771885678
Step: 15000, Loss: 40.317877188567806
Step: 16000, Loss: 40.317877188567806
Step: 17000, Loss: 40.317877188567806
Step: 18000, Loss: 40.317877188567806
Step: 19000, Loss: 40.317877188567806


In [23]:
# plt.title("Loss in first 1000 step")
# plt.xlabel("step")
# plt.ylabel("MSE")
# plt.plot(loss_history[4:1000])

In [24]:
w

array([ 26.84823285,  -0.03713233,  -1.19441498,   4.78243206,
        -4.86990311,  -1.28167819,  10.20506805, -11.17833838,
        -0.02825842,  19.33097146])

In [25]:
# 特征重要性
np.argsort(w)[::-1]

array([0, 9, 6, 3, 8, 1, 2, 5, 4, 7], dtype=int64)

> 可以发现，所有特征中第一天的观测值对结果影响最大，其次是最后一天。

## 测试集

In [26]:
df_test = pd.read_csv('../data/test(1).csv')
df_test = df_test[df_test['AMB_TEMP']=='PM2.5']
df_test.head()

id_0 AMB_TEMP  15  14 14.1  13 13.1 13.2 13.3 13.4  12
8   id_0    PM2.5  27  13   24  29   41   30   29   27  28
26  id_1    PM2.5  46  47   57  78   84   76   59   61  61
44  id_2    PM2.5  10  10   25  34   40   39   36   25  22
62  id_3    PM2.5  71  58   51  41   41   46   43   34  29
80  id_4    PM2.5  13  23   18  10    5    5   13    9  12

In [27]:
test_data = df_test.iloc[:, 2:]
test_data.head()

15  14 14.1  13 13.1 13.2 13.3 13.4  12
8   27  13   24  29   41   30   29   27  28
26  46  47   57  78   84   76   59   61  61
44  10  10   25  34   40   39   36   25  22
62  71  58   51  41   41   46   43   34  29
80  13  23   18  10    5    5   13    9  12

In [28]:
test_data = test_data.convert_objects(convert_numeric=True)

C:\Users\yinyajun-hj\AppData\Local\Programs\Python\Python35\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


In [29]:
test_data = ss.fit(test_data)
test_data.head()

15        14      14.1        13      13.1      13.2      13.3  \
8   0.304537 -0.644618  0.012649  0.281544  0.972881  0.260232  0.168454   
26  1.532221  1.532299  2.100491  3.317321  3.598760  3.029781  1.956900   
44 -0.793918 -0.836699  0.075917  0.591317  0.911814  0.802100  0.585758   
62  3.147595  2.236595  1.720884  1.024999  0.972881  1.223553  1.003062   
80 -0.600073 -0.004348 -0.366958 -0.895594 -1.225528 -1.244958 -0.785383   

        13.4        12  
8   0.023151  0.069481  
26  2.033514  2.008308  
44 -0.095105 -0.283033  
62  0.437050  0.128233  
80 -1.041158 -0.870557

In [30]:
test_x = np.array(test_data, float)
test_x=np.concatenate((np.ones((test_x.shape[0],1)),test_x),axis=1)
test_x.shape

(240, 10)

In [31]:
# 预测
y_hat = np.dot(test_x, w)
y_hat[:10]

array([ 27.16447254,  62.04842584,  20.3609033 ,  29.79177169,
        10.3280651 ,  37.98108691,  39.89435714,  16.65322075,
        48.93215638,  33.93006767])

In [32]:
# 对比答案
y_submit = pd.read_csv('../data/sampleSubmission.csv')
y_submit.value = y_hat
real = pd.read_csv("../data/answer.csv")


In [33]:
# 评价指标
sse = ((y_hat - real.value)**2).sum()
mse = ((y_hat - real.value)**2).mean()
rmse = np.sqrt(mse)
mae = np.abs(y_hat - real.value).mean()

ssr = ((y_hat- real.value.mean())**2).sum()
sst = ((real.value- real.value.mean())**2).sum()

r2 = 1 - sse / sst

from sklearn.metrics import r2_score
r2_score(real.value, y_hat)

0.9134110141646864

In [34]:
r2

0.9134110141646864

In [35]:
# 因为e和X相关，所以sst=ssr+sse不成立
sst - sse == ssr

False

In [36]:
mse 

42.439691259989814

In [37]:
rmse

6.5145752939074866

In [38]:
mae

4.9141342684929361